/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.rent.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.rent.bean.User;
import com.rent.service.IUserService;
import com.rent.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2014
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;
		String user_id=loginForm.getUser_id();
		String user_password=loginForm.getUser_password();
		ActionForward forward=mapping.getInputForward();
		IUserService service=(IUserService)getBean("userService");
		User userFormDB =service.getUserById(user_id);
		if(userFormDB.getUser_password().equals(user_password)){
			forward=mapping.findForward("suc");
			
		}
		return forward;
	}
}